import styles from '../../styles/layout.module.css'
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useRef, useState } from "react";
import NET from "vanta/dist/vanta.cells.min";
import * as THREE from "three";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faBullseye, faShieldVirus } from "@fortawesome/free-solid-svg-icons";


export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Monkeypox App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.navbar}>
                <div className={styles.navbarItems}>
                    <Link href="/">
                        <FontAwesomeIcon
                            icon={faShieldVirus}
                            style={{ fontSize: 25 }}
                            className={styles.navbarLogoItem}
                        /></Link>
                    {/* <div className={styles.navbarSubItems}>
                        <Link href="/">Home</Link>
                        <Link href="/">About</Link>
                        </div> */}
                    <Link href="/about">About</Link>
                </div>
            </div>

            <div className={styles.content}>
                {children}
            </div>

        </>
    )
}